In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

import matplotlib.pyplot as plt
import seaborn as  sns

In [2]:
df = pd.read_csv('(Titanic)train.csv',usecols =['Age','Fare','Survived'])
df.sample(6)

Survived   Age      Fare
68          1  17.0    7.9250
471         0  38.0    8.6625
537         1  30.0  106.4250
148         0  36.5   26.0000
54          0  65.0   61.9792
58          1   5.0   27.7500

In [3]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [4]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [6]:
X_train

Age      Fare
332  38.0  153.4625
281  28.0    7.8542
147   9.0   34.3750
11   58.0   26.5500
405  34.0   21.0000
..    ...       ...
725  20.0    8.6625
607  27.0   30.5000
544  50.0  106.4250
643   NaN   56.4958
414  44.0    7.9250

[712 rows x 2 columns]

In [7]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [8]:
X_train_trf

array([[ 38.        , 153.4625    ],
       [ 28.        ,   7.8542    ],
       [  9.        ,  34.375     ],
       ...,
       [ 50.        , 106.425     ],
       [ 29.93955986,  56.4958    ],
       [ 44.        ,   7.925     ]])

In [9]:
from sklearn.linear_model import LogisticRegression

clf  = LogisticRegression()
clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6759776536312849

In [10]:
mi = MissingIndicator()
mi.fit(X_train)

MissingIndicator()

In [11]:
X_train_missing = mi.transform(X_train)
X_test_missing = mi.transform(X_test)

In [12]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [13]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [14]:
X_train['Age_na'] = X_train_missing
X_test['Age_na'] = X_test_missing

C:\Users\nagam\AppData\Local\Temp/ipykernel_16704/3187878572.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age_na'] = X_train_missing
C:\Users\nagam\AppData\Local\Temp/ipykernel_16704/3187878572.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Age_na'] = X_test_missing


In [15]:
X_train

Age      Fare  Age_na
332  38.0  153.4625   False
281  28.0    7.8542   False
147   9.0   34.3750   False
11   58.0   26.5500   False
405  34.0   21.0000   False
..    ...       ...     ...
725  20.0    8.6625   False
607  27.0   30.5000   False
544  50.0  106.4250   False
643   NaN   56.4958    True
414  44.0    7.9250   False

[712 rows x 3 columns]

In [16]:
si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [17]:
from sklearn.linear_model import LogisticRegression

clf  = LogisticRegression()
clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.659217877094972

In [18]:
si = SimpleImputer(add_indicator=True)

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [20]:
X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [21]:
from sklearn.linear_model import LogisticRegression

clf  = LogisticRegression()
clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.659217877094972